<?php

namespace ContainerE1fn0XO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntervention_Image_FactoryService extends Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'intervention.image.factory' shared service.
     *
     * @return \Intervention\Image\ImageManagerStatic
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php';

        return $container->services['intervention.image.factory'] = new \Intervention\Image\ImageManagerStatic();
    }
}
