<?php

namespace ContainerE1fn0XO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJanwebdev_Intervention_ImageService extends Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'janwebdev.intervention.image' shared service.
     *
     * @return \Janwebdev\ImageBundle\Image
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Image.php';
        include_once \dirname(__DIR__, 4).'/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php';

        return $container->services['janwebdev.intervention.image'] = new \Janwebdev\ImageBundle\Image(($container->services['intervention.image.factory'] ?? ($container->services['intervention.image.factory'] = new \Intervention\Image\ImageManagerStatic())));
    }
}
