services:
    janwebdev.intervention.image:
        class: Janwebdev\ImageBundle\Image
        arguments: ["@intervention.image.factory"]
        public: false

    intervention.image.factory:
        class: Intervention\Image\ImageManagerStatic
        public: false