<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
(require __DIR__.'/Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer.php')->set(\ContainerE1fn0XO\Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer::class, null);
require __DIR__.'/ContainerE1fn0XO/getJanwebdev_Intervention_ImageService.php';
require __DIR__.'/ContainerE1fn0XO/getIntervention_Image_FactoryService.php';

$classes = [];
$classes[] = 'Janwebdev\ImageBundle\ImageBundle';
$classes[] = 'Intervention\Image\ImageManagerStatic';
$classes[] = 'Janwebdev\ImageBundle\Image';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
