<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE1fn0XO\Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE1fn0XO/Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerE1fn0XO.legacy');

    return;
}

if (!\class_exists(Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerE1fn0XO\Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer::class, Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer::class, false);
}

return new \ContainerE1fn0XO\Janwebdev_ImageBundle_Tests_TestKernelTestDebugContainer([
    'container.build_hash' => 'E1fn0XO',
    'container.build_id' => '6f32756a',
    'container.build_time' => 1654608712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE1fn0XO');
